-- PKRS BMI schema for Supabase
-- Run in Supabase SQL Editor

create table if not exists public.bmi_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  instansi text not null check (char_length(trim(instansi)) > 0),
  phone_number text check (phone_number is null or phone_number ~ '^62[0-9]{8,15}$'),
  gender text not null check (gender in ('Laki-laki', 'Perempuan')),
  weight_kg numeric(5,2) not null check (weight_kg >= 20 and weight_kg <= 300),
  height_cm numeric(5,2) not null check (height_cm >= 80 and height_cm <= 250),
  age integer not null check (age >= 5 and age <= 120),
  bmi numeric(4,1) not null check (bmi > 0),
  category text not null check (category in ('BB Kurang', 'Kurus', 'Normal', 'BB Berlebih', 'Obesitas')),
  created_at timestamptz not null default now()
);

create index if not exists idx_bmi_submissions_created_at
  on public.bmi_submissions (created_at desc);

-- Enable RLS and allow anon client access used by this app.
-- NOTE: This allows public read/insert using anon key.
alter table public.bmi_submissions enable row level security;

drop policy if exists "anon can insert bmi submissions" on public.bmi_submissions;
create policy "anon can insert bmi submissions"
  on public.bmi_submissions
  for insert
  to anon
  with check (true);

drop policy if exists "anon can select bmi submissions" on public.bmi_submissions;
create policy "anon can select bmi submissions"
  on public.bmi_submissions
  for select
  to anon
  using (true);

-- Food estimator reference table (cached nutrition per food item)
create extension if not exists pg_trgm;

create table if not exists public.food_items (
  id bigint generated by default as identity primary key,
  name text not null,
  name_local text not null,
  default_grams numeric(7,2) not null default 100 check (default_grams >= 0),
  calories_per_100g numeric(8,2) not null default 0 check (calories_per_100g >= 0),
  carbs_per_100g numeric(8,2) not null default 0 check (carbs_per_100g >= 0),
  protein_per_100g numeric(8,2) not null default 0 check (protein_per_100g >= 0),
  fat_per_100g numeric(8,2) not null default 0 check (fat_per_100g >= 0),
  recognition_count integer not null default 0 check (recognition_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_food_items_name_trgm
  on public.food_items using gin (name gin_trgm_ops);

create index if not exists idx_food_items_name_local_trgm
  on public.food_items using gin (name_local gin_trgm_ops);

create index if not exists idx_food_items_recognition_count
  on public.food_items (recognition_count desc);

create table if not exists public.food_logs (
  id bigint generated by default as identity primary key,
  meal_type text not null check (meal_type in ('Sarapan', 'Makan Siang', 'Makan Malam', 'Snack')),
  foods jsonb not null,
  total_calories numeric(8,2) not null check (total_calories >= 0),
  total_carbs_g numeric(8,2) not null check (total_carbs_g >= 0),
  total_protein_g numeric(8,2) not null check (total_protein_g >= 0),
  total_fat_g numeric(8,2) not null check (total_fat_g >= 0),
  was_corrected boolean not null default false,
  source text not null check (source in ('openai', 'database')),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_food_logs_created_at
  on public.food_logs (created_at desc);

-- Stronger DB-first fuzzy search with pg_trgm ranking
create extension if not exists pg_trgm;

create index if not exists idx_food_items_name_trgm_rank
  on public.food_items using gin (name gin_trgm_ops);

create index if not exists idx_food_items_name_local_trgm_rank
  on public.food_items using gin (name_local gin_trgm_ops);

create or replace function public.search_food_items_trgm(
  query_text text,
  min_similarity float default 0.2,
  max_results int default 10
)
returns table (
  id uuid,
  name text,
  name_local text,
  calories_per_100g numeric,
  carbs_per_100g numeric,
  protein_per_100g numeric,
  fat_per_100g numeric,
  recognition_count integer,
  similarity_score float
)
language sql
stable
as $$
  select
    fi.id,
    fi.name,
    fi.name_local,
    fi.calories_per_100g,
    fi.carbs_per_100g,
    fi.protein_per_100g,
    fi.fat_per_100g,
    fi.recognition_count,
    greatest(
      similarity(lower(coalesce(fi.name, '')), lower(coalesce(query_text, ''))),
      similarity(lower(coalesce(fi.name_local, '')), lower(coalesce(query_text, '')))
    ) as similarity_score
  from public.food_items fi
  where greatest(
    similarity(lower(coalesce(fi.name, '')), lower(coalesce(query_text, ''))),
    similarity(lower(coalesce(fi.name_local, '')), lower(coalesce(query_text, '')))
  ) >= min_similarity
  order by similarity_score desc, fi.recognition_count desc
  limit greatest(max_results, 1);
$$;
