-- PKRS BMI schema for Supabase
-- Run in Supabase SQL Editor

create table if not exists public.bmi_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  instansi text not null check (char_length(trim(instansi)) > 0),
  phone_number text not null check (phone_number ~ '^62[0-9]{8,15}$'),
  gender text not null check (gender in ('Laki-laki', 'Perempuan')),
  weight_kg numeric(5,2) not null check (weight_kg >= 20 and weight_kg <= 300),
  height_cm numeric(5,2) not null check (height_cm >= 80 and height_cm <= 250),
  age integer not null check (age >= 5 and age <= 120),
  bmi numeric(4,1) not null check (bmi > 0),
  category text not null check (category in ('Kurus', 'Normal', 'Gemuk', 'Obesitas')),
  created_at timestamptz not null default now()
);

create index if not exists idx_bmi_submissions_created_at
  on public.bmi_submissions (created_at desc);

-- Enable RLS and allow anon client access used by this app.
-- NOTE: This allows public read/insert using anon key.
alter table public.bmi_submissions enable row level security;

drop policy if exists "anon can insert bmi submissions" on public.bmi_submissions;
create policy "anon can insert bmi submissions"
  on public.bmi_submissions
  for insert
  to anon
  with check (true);

drop policy if exists "anon can select bmi submissions" on public.bmi_submissions;
create policy "anon can select bmi submissions"
  on public.bmi_submissions
  for select
  to anon
  using (true);
